/** Códigos de tipo de notificación (extensibles por escenario). */
export const TipoNotificacion = {
  ALQUILER_VENCIDO: 'ALQUILER_VENCIDO',
  ALQUILER_POR_VENCER: 'ALQUILER_POR_VENCER',
  PRESTAMO_VENCIDO: 'PRESTAMO_VENCIDO',
  PRESTAMO_POR_VENCER: 'PRESTAMO_POR_VENCER',
  BAJA_CILINDRO_SOLICITADA: 'BAJA_CILINDRO_SOLICITADA',
  BAJA_CILINDRO_APROBADA: 'BAJA_CILINDRO_APROBADA',
  BAJA_CILINDRO_RECHAZADA: 'BAJA_CILINDRO_RECHAZADA',
  BAJA_CLIENTE_SOLICITADA: 'BAJA_CLIENTE_SOLICITADA',
  BAJA_CLIENTE_APROBADA: 'BAJA_CLIENTE_APROBADA',
  BAJA_CLIENTE_RECHAZADA: 'BAJA_CLIENTE_RECHAZADA',
  REACTIVACION_CLIENTE_SOLICITADA: 'REACTIVACION_CLIENTE_SOLICITADA',
  REACTIVACION_CLIENTE_APROBADA: 'REACTIVACION_CLIENTE_APROBADA',
  REACTIVACION_CLIENTE_RECHAZADA: 'REACTIVACION_CLIENTE_RECHAZADA',
  COMPROBANTE_SUNAT_RECHAZADO: 'COMPROBANTE_SUNAT_RECHAZADO',
  COMPROBANTE_ERROR_EMISION: 'COMPROBANTE_ERROR_EMISION',
  COMPROBANTE_SUNAT_PENDIENTE: 'COMPROBANTE_SUNAT_PENDIENTE',
  GUIA_SUNAT_RECHAZADA: 'GUIA_SUNAT_RECHAZADA',
  GUIA_ERROR_EMISION: 'GUIA_ERROR_EMISION',
  GUIA_SUNAT_PENDIENTE: 'GUIA_SUNAT_PENDIENTE',
  DOCUMENTO_POR_VENCER: 'DOCUMENTO_POR_VENCER',
  DOCUMENTO_VENCIDO: 'DOCUMENTO_VENCIDO',
  LICENCIA_POR_VENCER: 'LICENCIA_POR_VENCER',
  LICENCIA_VENCIDA: 'LICENCIA_VENCIDA',
  STOCK_BAJO: 'STOCK_BAJO',
  STOCK_CERO: 'STOCK_CERO',
  SISTEMA: 'SISTEMA',
  USUARIO: 'USUARIO',
} as const;

export type TipoNotificacionCodigo =
  (typeof TipoNotificacion)[keyof typeof TipoNotificacion];

export const TipoReferenciaNotificacion = {
  ALQUILER: 'ALQUILER',
  PRESTAMO: 'PRESTAMO',
  BALON: 'BALON',
  CLIENTE: 'CLIENTE',
  COMPROBANTE: 'COMPROBANTE',
  GUIA_REMISION: 'GUIA_REMISION',
  DOCUMENTO_VENCIMIENTO: 'DOCUMENTO_VENCIMIENTO',
  LICENCIA: 'LICENCIA',
  STOCK: 'STOCK',
  USUARIO: 'USUARIO',
  SISTEMA: 'SISTEMA',
} as const;
