-- Solo para una base temporal vacía. Fixture mínimo de la migración.
CREATE TABLE gen_empresa(id integer PRIMARY KEY, ruc varchar(11), estado integer);
CREATE TABLE gen_lista_opciones(id integer PRIMARY KEY, nombre varchar(50), descripcion varchar(50));
CREATE TABLE doc_salida (
    id integer NOT NULL,
    numero character varying(30) NOT NULL,
    id_tipo_orden integer NOT NULL,
    id_estado_ciclo integer NOT NULL,
    emitido_sunat boolean DEFAULT false NOT NULL,
    id_venta integer,
    id_doc_salida_origen integer,
    id_sucursal integer NOT NULL,
    -- Almacén de origen: de dónde salieron los cilindros/productos. No lo pisa
    -- el retorno de planta externa (ver id_almacen_retorno).
    id_almacen integer NOT NULL,
    id_almacen_destino integer,
    -- Almacén al que llegaron los cilindros al volver de planta externa.
    id_almacen_retorno integer,
    id_cliente integer,
    id_destinatario integer,
    id_proveedor integer,
    fecha date NOT NULL,
    fecha_traslado date,
    fecha_retorno date,
    id_tipo_guia_remision integer,
    serie character varying(10),
    numero_sunat character varying(15),
    id_estado_sunat integer,
    ticket_sunat character varying(100),
    hash_documento character varying(100),
    xml_firmado text,
    cdr_respuesta text,
    tipo_cambio numeric(10,4) DEFAULT 3.5,
    id_motivo_traslado integer,
    id_modalidad_traslado integer,
    id_unidad_medida integer,
    peso_bruto numeric(10,4),
    numero_bultos integer,
    direccion_origen character varying(255),
    id_distrito_origen integer,
    direccion_llegada character varying(255),
    id_distrito_llegada integer,
    id_transportista integer,
    id_chofer integer,
    id_vehiculo integer,
    id_responsable integer,
    destinatario_nombre character varying(255),
    destinatario_documento character varying(20),
    remitente_nombre character varying(255),
    remitente_documento character varying(20),
    id_comprobante_compra integer,
    serie_guia_salida character varying(10),
    numero_guia_salida character varying(15),
    serie_guia_ingreso character varying(10),
    numero_guia_ingreso character varying(15),
    serie_factura character varying(10),
    numero_factura character varying(15),
    fecha_llegada_almacen date,
    lote character varying(50),
    fecha_vencimiento_lote date,
    fecha_prueba_hidrostatica date,
    periodo_contable character varying(10),
    operacion character varying(100),
    observaciones character varying(500),
    id_archivo_pdf integer,
    estado integer DEFAULT 1 NOT NULL,
    id_usuario_creacion integer,
    id_usuario_modificacion integer,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    fecha_modificacion timestamp without time zone
);
